### ISSUE TITLE
Separere steder for stillingsannonser

### ISSUE THREAD

**Issue by sigtot** [Nettverksdagen/Nettverksdagen-2#10]
Dette her vil ikke fungere særlig bra. Ser ut til at de fleste stillingsannonser lyser ut flere lokasjoner samtidig, så dette er normen heller enn unntaket.
![steder](https://user-images.githubusercontent.com/5937246/51495457-b0df6b80-1dbc-11e9-921b-93c739393b6b.png)

Den enkleste løsningen på dette tenker jeg å lagre en liste med kommaseparerte verdier i databasen, også generere en liste ut i fra dette i frontend.

**Comment by einarmo** [comment]
Hvis du er litt lur så fjerner du alle ord som starter på liten bokstav, alle tegn komma, punktum og mellomrom, og splitter på ord. Du kan fint gjøre den operasjonen rent i frontend, det er ikke nødvendig å øke kompleksiteten serverside.

**Comment by sigtot** [comment]
Tenkte ikke gjøre noe server side nei. Bare bare splitte på komma og mellomrom i frontend.
