### ISSUE TITLE
Oppretting av admin-brukere

### ISSUE THREAD

**Issue by sigtot** [Nettverksdagen/Nettverksdagen-2#15]
Tror dette også er noenlunde "innebygd" i django-rest-auth

**Comment by olejodd10** [comment]
Har vi i det hele tatt lyst til å ha en superbruker-oppretting på adminsiden? Det er jo ønskelig at kun IT-gruppen kan lage superbrukere, siden alt annet er veldig utrygt. Og en admin-funksjonalitet som kun kan brukes av én bruker (IT-gruppen) er jo både rotete og unødvendig.

**Comment by olejodd10** [comment]
IT-gruppen 2022 synes dette er en dårlig idé ref kommentar over.
